spring.application.name=OxideBingo
#spring.devtools.livereload.enabled=true
#spring.devtools.livereload.port=35729
#spring.devtools.restart.enabled=true
#spring.thymeleaf.cache=false
#server.servlet.context-path=/oxidebingo